import { NullFile } from "./FileOrbit";

export const NOLLTECH_WRITINGS: NullFile[] = [
  { name: "Magi v1", type: "txt", path: "/nolltech/Magi v1.txt" },
  { name: "NullAegis v1", type: "txt", path: "/nolltech/NullAegis v1.txt" },
  { name: "NullArk v1", type: "txt", path: "/nolltech/NullArk v1.txt" },
  { name: "NullBilliards v1", type: "txt", path: "/nolltech/NullBilliards v1.txt" },
  { name: "NullBridge v1", type: "txt", path: "/nolltech/NullBridge v1.txt" },
  { name: "NullChronicle v1", type: "txt", path: "/nolltech/NullChronicle v1.txt" },
  { name: "NullCortex v1", type: "txt", path: "/nolltech/NullCortex v1.txt" },
  { name: "NullDeck v1", type: "txt", path: "/nolltech/NullDeck v1.txt" },
  { name: "NullDisk v1", type: "txt", path: "/nolltech/NullDisk v1.txt" },
  { name: "NullEmber v1", type: "txt", path: "/nolltech/NullEmber v1.txt" },
  { name: "NullForge v1", type: "txt", path: "/nolltech/NullForge v1.txt" },
  { name: "NullHover v1", type: "txt", path: "/nolltech/NullHover v1.txt" },
  { name: "NullLoom v1", type: "txt", path: "/nolltech/NullLoom v1.txt" },
  { name: "NullMind v1", type: "txt", path: "/nolltech/NullMind v1.txt" },
  { name: "NullRoot v1", type: "txt", path: "/nolltech/NullRoot v1.txt" },
  { name: "NullShell v1", type: "txt", path: "/nolltech/NullShell v1.txt" },
  { name: "NullStuture v1", type: "txt", path: "/nolltech/NullStuture v1.txt" },
  { name: "NullThread v1", type: "txt", path: "/nolltech/NullThread v1.txt" },
  { name: "Nullware v1", type: "txt", path: "/nolltech/Nullware v1.txt" },
  { name: "NullWellspring v1", type: "txt", path: "/nolltech/NullWellspring v1.txt" },
  { name: "OrbitOS v1", type: "txt", path: "/nolltech/OrbitOS v1.txt" },
  { name: "TheNullLineProject", type: "txt", path: "/nolltech/TheNullLineProject.txt" },
];
